# User config
author: "hoony"
tagline: "Developer"
description: "제주대학교 컴퓨터공학전공 현지훈<br>iOS Developer"
keywords: "hoony, 자기소개서"
email: "z@hoony.org"
github: "https://github.com/z-hoony"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
theme: jekyll-theme-cayman